<a href="https://colab.research.google.com/github/25wh1a0502/NASSCOM-Lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1 = np.arange(0, 12, 4)
print("Array using arange:", arr1)


Array using arange: [0 4 8]


In [ ]:
import numpy as np
arr2 = np.linspace(0, 1, 10)
print("Array using linspace:", arr2)


Array using linspace: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())


Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [ ]:
data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)

Original Data:
 [[5 8 9]
 [2 4 6]]


In [ ]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))


Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [ ]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [ ]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)

Original Array: [3 1 7 2 9]


In [ ]:
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 5)
print("Indices where value > 5:", idx)
print("Values > 5:", a[idx])

Sorted Array: [1 2 3 7 9]
Indices where value > 5: (array([2, 4]),)
Values > 5: [7 9]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 10])

print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[1 2]
 [3 4]]
Vector B: [ 5 10]


In [ ]:
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[ 6 12]
 [ 8 14]]


In [ ]:
nums = np.array([1, 3, 5, 7, 9])
mask = nums > 3
print("Mask (nums > 3):", mask)


Mask (nums > 3): [False False  True  True  True]


In [ ]:

filtered = nums[mask]
print("Filtered values:", filtered)

result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [5 7 9]
Even or Odd: ['Odd' 'Odd' 'Odd' 'Odd' 'Odd']


In [ ]:
arr_orig = np.array([5, 10, 20])
arr_view = arr_orig[:]
arr_view[0] = 99
print("Original After View Change:", arr_orig)


Original After View Change: [99 10 20]


In [ ]:
arr_copy = arr_orig.copy()
arr_copy[0] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

Original After Copy Change: [99 10 20]
Copy: [55 10 20]


In [ ]:
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[10 20 30]
 [40 50 60]]


In [ ]:
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
z = np.arange(30)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

Horizontal Stack:
 [10 20 30 40 50 60]
Split into 3 parts: [array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]


In [ ]:
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)

Random Integers:
 [[43 58 76]
 [81 28 17]
 [82 46 42]]
Random Normal Distribution:
 [[-1.42176428 -1.11044939  0.12281098 -0.42818328]
 [ 1.40558864 -0.83075303 -1.03561143  1.43267751]]


In [ ]:

choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [3 3 5 5 5]
Seeded Random Number: 0.3745401188473625


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])

Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [ ]:
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [ ]:

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])
mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
